=== ShundytheFox/ProyectoLND/LNDProject/VR.dtd
<!ELEMENT VrHeadsets (VrHeadset+)>
<!ELEMENT VrHeadset (VrName,Date,Tracking,CreatorName,Purpose,Description,Price,TechnicalAspects)>
<!ELEMENT VrName (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Tracking (HeadTracking,HandTracking,FullbodyTracking)>
<!ELEMENT HeadTracking (#PCDATA)>
<!ELEMENT HandTracking (#PCDATA)>
<!ELEMENT FullbodyTracking (#PCDATA)>
<!ELEMENT CreatorName (#PCDATA)>
<!ELEMENT Purpose (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT TechnicalAspects (Resolution,FieldOfView,IntegratedSpeakers)>
<!ELEMENT Resolution (#PCDATA)>
<!ELEMENT FieldOfView (#PCDATA)>
<!ELEMENT IntegratedSpeakers (#PCDATA)>
<!ATTLIST VrHeadset ID CDATA #REQUIRED>

=== ShundytheFox/ProyectoLND/VR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE VrHeadsets SYSTEM "VR.dtd">

<VrHeadsets>
    <VrHeadset ID="100">
        <VrName>Sensorama</VrName>
        <Date>1956</Date>
        <Tracking>
            <HeadTracking>No</HeadTracking>
            <HandTracking>No</HandTracking>
            <FullbodyTracking>No</FullbodyTracking>
        </Tracking>
        <CreatorName>Morton Heilig</CreatorName>
        <Purpose>Visualizar películas</Purpose>
        <Description>
            Primer visor de VR. Combinaba vídeo en 3D, audio, vibraciones y efectos atmosféricos.
            Esto se hacía usando productos de aroma, una silla vibratoria, altavoces stereo y una pantalla 3D.
        </Description>
        <Price>Desconocido</Price>
        <TechnicalAspects>
            <Resolution>Desconocida</Resolution>
            <FieldOfView>Desconocido</FieldOfView>
            <IntegratedSpeakers>Sí</IntegratedSpeakers>
        </TechnicalAspects>
    </VrHeadset>

    <VrHeadset ID="101">
        <VrName>The Sword of Damocles</VrName>
        <Date>1968</Date>
        <Tracking>
            <HeadTracking>Sí</HeadTracking>
            <HandTracking>No</HandTracking>
            <FullbodyTracking>No</FullbodyTracking>
        </Tracking>
        <CreatorName>Ivan Sutherland y Bob Sproull</CreatorName>
        <Purpose>Visualizar formas simples</Purpose>
        <Description>
            El visor tenía una forma que recuerda a los headset de VR actuales, y estaba conectada a un PC.
            Además, hacía un seguimiento de la cabeza y las formas cambiaban de perspectiva.   
        </Description>
        <Price>Desconocido</Price>
        <TechnicalAspects>
            <Resolution>Desconocida</Resolution>
            <FieldOfView>Desconocido</FieldOfView>
            <IntegratedSpeakers>No</IntegratedSpeakers>
        </TechnicalAspects>
    </VrHeadset>

    <VrHeadset ID="102">
        <VrName>Virtual Environment Workstation</VrName>
        <Date>1989</Date>
        <Tracking>
            <HeadTracking>Sí</HeadTracking>
            <HandTracking>Sí</HandTracking>
            <FullbodyTracking>No</FullbodyTracking>
        </Tracking>
        <CreatorName>NASA</CreatorName>
        <Purpose>Entrenamiento para astronautas</Purpose>
        <Description>
            Contenía unos guantes que permitían interactuar con los objetos dentro de las VR y un sistema de audio 3D.  
        </Description>
        <Price>Desconocido</Price>
        <TechnicalAspects>
            <Resolution>Desconocida</Resolution>
            <FieldOfView>Desconocido</FieldOfView>
            <IntegratedSpeakers>Sí</IntegratedSpeakers>
        </TechnicalAspects>
    </VrHeadset>

    <VrHeadset ID="103">
        <VrName>Virtual Boy</VrName>
        <Date>1995</Date>
        <Tracking>
            <HeadTracking>Sí</HeadTracking>
            <HandTracking>No</HandTracking>
            <FullbodyTracking>No</FullbodyTracking>
        </Tracking>
        <CreatorName>Nintendo</CreatorName>
        <Purpose>Vídeojuegos</Purpose>
        <Description>
            Era una consola semi-portatil que solo funcionaba con las VR. Con apenas apoyo de software fue descatalogada.
            Además, era considerada incómoda y sus prestaciones muy limitadas.
        </Description>
        <Price>200€</Price>
        <TechnicalAspects>
            <Resolution>384x224</Resolution>
            <FieldOfView>Desconocido</FieldOfView>
            <IntegratedSpeakers>Sí</IntegratedSpeakers>
        </TechnicalAspects>
    </VrHeadset>

    <VrHeadset ID="104">
        <VrName>Oculus Rift CV1</VrName>
        <Date>2016</Date>
        <Tracking>
            <HeadTracking>Sí</HeadTracking>
            <HandTracking>Sí</HandTracking>
            <FullbodyTracking>Parcialmente</FullbodyTracking>
        </Tracking>
        <CreatorName>Oculus - Facebook</CreatorName>
        <Purpose>Vídeojuegos</Purpose>
        <Description>
            Primera generación de VR moderna. Estuvo en desarrollo muchos años mediante financiación colectiva.
            Finalmente fue comprada por Facebook y supuso un antes y un después en el mundo de la Realidad Virtual.
        </Description>
        <Price>600€</Price>
        <TechnicalAspects>
            <Resolution>1080x1200</Resolution>
            <FieldOfView>110º</FieldOfView>
            <IntegratedSpeakers>Sí</IntegratedSpeakers>
        </TechnicalAspects>
    </VrHeadset>

    <VrHeadset ID="105">
        <VrName>Valve</VrName>
        <Date>2019</Date>
        <Tracking>
            <HeadTracking>Sí</HeadTracking>
            <HandTracking>Sí</HandTracking>
            <FullbodyTracking>Parcialmente</FullbodyTracking>
        </Tracking>
        <CreatorName>Valve</CreatorName>
        <Purpose>Vídeojuegos</Purpose>
        <Description>
            Visor de segunda generación, mucho más moderno y actual. Tiene casi todas las prestaciones que se pueden esperar.
            Desarrollada por la empresa creadora de Steam, utiliza el software "SteamVR".
        </Description>
        <Price>1040€</Price>
        <TechnicalAspects>
            <Resolution>1440x1600</Resolution>
            <FieldOfView>130º</FieldOfView>
            <IntegratedSpeakers>Sí</IntegratedSpeakers>
        </TechnicalAspects>
    </VrHeadset>
</VrHeadsets>
